import type { RCAReport } from './types'

// ─── Severity badge ───────────────────────────────────────────────────────────

function severityBadge(severity: RCAReport['overallSeverity']): string {
    const badges = {
        critical: '🔴 CRITICAL',
        high: '🟠 HIGH',
        medium: '🟡 MEDIUM',
        low: '🟢 LOW'
    }
    return badges[severity]
}

// ─── Confidence bar ───────────────────────────────────────────────────────────
// Renders a text-based confidence indicator.
// 0.85 → ████████░░ 85%

function confidenceBar(confidence: number): string {
    const filled = Math.round(confidence * 10)
    const empty = 10 - filled
    const bar = '█'.repeat(filled) + '░'.repeat(empty)
    const pct = Math.round(confidence * 100)
    return `${bar} ${pct}%`
}

// ─── Markdown formatter ───────────────────────────────────────────────────────

export function formatAsMarkdown(report: RCAReport): string {
    const lines: string[] = []

    // Header
    lines.push('# Root Cause Analysis Report')
    lines.push('')
    lines.push(`> Generated: ${report.generatedAt}`)
    lines.push(`> Source: \`${report.sourceFile}\``)
    lines.push(`> Lines analyzed: ${report.totalLines.toLocaleString()} across ${report.chunksAnalyzed} chunk(s)`)
    lines.push('')

    // Summary box
    lines.push('---')
    lines.push('')
    lines.push('## Summary')
    lines.push('')
    lines.push(`| Field | Value |`)
    lines.push(`|-------|-------|`)
    lines.push(`| Severity | ${severityBadge(report.overallSeverity)} |`)
    lines.push(`| Confidence | ${confidenceBar(report.confidence)} |`)
    lines.push(`| Affected Services | ${report.affectedServices.join(', ') || 'None identified'} |`)
    lines.push('')

    // Root cause — the most important section
    lines.push('---')
    lines.push('')
    lines.push('## Root Cause')
    lines.push('')
    lines.push(`> ${report.rootCause}`)
    lines.push('')

    // Timeline
    if (report.timeline.length > 0) {
        lines.push('---')
        lines.push('')
        lines.push('## Incident Timeline')
        lines.push('')
        report.timeline.forEach(event => {
            lines.push(`- **${event.timestamp}** — ${event.event}`)
        })
        lines.push('')
    }

    // Evidence
    if (report.evidence.length > 0) {
        lines.push('---')
        lines.push('')
        lines.push('## Supporting Evidence')
        lines.push('')
        lines.push('The following log lines directly support the root cause finding:')
        lines.push('')
        lines.push('```')
        report.evidence.forEach(line => lines.push(line))
        lines.push('```')
        lines.push('')
    }

    // Recommended actions
    if (report.recommendedActions.length > 0) {
        lines.push('---')
        lines.push('')
        lines.push('## Recommended Actions')
        lines.push('')
        report.recommendedActions.forEach((action, i) => {
            lines.push(`${i + 1}. ${action}`)
        })
        lines.push('')
    }

    // Per-chunk breakdown (collapsed section — useful for debugging)
    if (report.rawChunks.length > 1) {
        lines.push('---')
        lines.push('')
        lines.push('## Per-Chunk Analysis')
        lines.push('')
        lines.push('<details>')
        lines.push('<summary>Click to expand chunk-by-chunk breakdown</summary>')
        lines.push('')

        report.rawChunks.forEach((chunk, i) => {
            lines.push(`### Chunk ${i + 1}`)
            lines.push('')
            lines.push(`- **Severity:** ${severityBadge(chunk.severity)}`)
            lines.push(`- **Confidence:** ${confidenceBar(chunk.confidence)}`)
            lines.push(`- **Root Cause:** ${chunk.rootCause}`)

            if (chunk.affectedServices.length > 0) {
                lines.push(`- **Services:** ${chunk.affectedServices.join(', ')}`)
            }

            if (chunk.errorPatterns.length > 0) {
                lines.push(`- **Error Patterns:**`)
                chunk.errorPatterns.forEach(p => {
                    lines.push(`  - \`${p.pattern}\` — ${p.count}x (first seen: ${p.firstSeen})`)
                })
            }

            if (chunk.evidence.length > 0) {
                lines.push(`- **Evidence:**`)
                lines.push('  ```')
                chunk.evidence.slice(0, 3).forEach(e => lines.push(`  ${e}`))
                lines.push('  ```')
            }

            lines.push('')
        })

        lines.push('</details>')
        lines.push('')
    }

    // Footer
    lines.push('---')
    lines.push('')
    lines.push('*Report generated by log-rca — powered by Ollama (local LLM)*')
    lines.push('')

    return lines.join('\n')
}

// ─── JSON formatter ───────────────────────────────────────────────────────────
// Returns the full report as pretty-printed JSON.
// Useful for piping into other tools or storing in a database.

export function formatAsJSON(report: RCAReport): string {
    return JSON.stringify(report, null, 2)
}

// ─── Short summary (for stdout when --output is set) ─────────────────────────
// When the full report is written to a file, print a short summary to stdout
// so the user knows what was found without opening the file.

export function formatSummary(report: RCAReport): string {
    const lines: string[] = []

    lines.push('')
    lines.push('┌─────────────────────────────────────────┐')
    lines.push('│           RCA Report Summary             │')
    lines.push('└─────────────────────────────────────────┘')
    lines.push('')
    lines.push(`  Severity:   ${severityBadge(report.overallSeverity)}`)
    lines.push(`  Confidence: ${confidenceBar(report.confidence)}`)
    lines.push(`  Services:   ${report.affectedServices.join(', ') || 'None identified'}`)
    lines.push(`  Chunks:     ${report.chunksAnalyzed}`)
    lines.push('')
    lines.push(`  Root Cause:`)
    lines.push(`  ${report.rootCause}`)
    lines.push('')
    lines.push(`  Top Action:`)
    lines.push(`  ${report.recommendedActions[0] ?? 'No actions recommended'}`)
    lines.push('')

    return lines.join('\n')
}